name: mobile_prog_test_2
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  easy_refresh: ^3.0.4+2
  fancy_shimmer_image: ^2.0.2
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.6.2
  get: 4.6.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
